<div class="rodape">
    <div class="container">
        
        <div id="logo_rodape" onclick="window.location.href='/'"><img src="<?=$this->BaseUrl("img/logoTerrativaBranca.png");?>" /></div>
        
        <ul>
            <li><a href="/">INICIAL</a></li>
            <li><a href="/quem-somos">QUEM SOMOS</a></li>
            <!--<li><a href="/maquiagem">MAQUIAGEM</a></li>
            <li><a href="/estetica">ESTÉTICA</a></li>-->
            <li><a href="/cursos">CURSOS</a></li>
            <li><a href="/produtos">PRODUTOS</a></li>
            <li><a href="/contato">CONTATO</a></li>
        </ul>
    </div>
    
    <div class="assinaturas">
        <div id="texto">TODOS OS DIREITOS RESERVADOS - TERRATIVA COSMÉTICOS E ESTÉTICA <br/> RUA PIAUÍ, 399 - SALA 6 - LONDRINA-PR | Fone: (43) 3323-9043</div>
        <div id="assPrimage"><a href="http://www.primage.com.br" target="_blank"><img src="<?=$this->BaseUrl("img/assPrimage.png");?>" /></a></div>
    </div>
</div>
