<?php header("Content-Type: text/html; charset=ISO-8859-1",true) ?>
<link href="<?=$this->BaseUrl('js/lib/jquery-ui-1.8.16.custom/css/ui-darkness/jquery-ui-1.8.16.custom.css');?>" rel="stylesheet" media="screen" type="text/css" />

<link href="<?=$this->BaseUrl('_primage/default/css/layout.css');		?>" rel="stylesheet" type="text/css" media="screen" />

<style>body, html{background:#fff !important;}</style>

<script src="<?=$this->BaseUrl('js/lib/jquery-ui-1.8.16.custom/js/jquery-1.6.2.min.js');			?>" type="text/javascript"></script>

<script src="<?=$this->BaseUrl('js/lib/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js');	?>" type="text/javascript"></script>
<script src="<?=$this->BaseUrl('js/formularios.js');	?>" type="text/javascript"></script>

<?=$this->headLink();?>

<?=$this->headScript();?>

<?=$this->layout()->content; ?>