<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Error 404 (Not Found)!!</title>
<style>
html, body { position: relative; margin: 0px; padding: 0px; width: 100%; height: 100%;}
#error 	   { width: 500px; min-height: 200px; height: auto !important; background: #FFF; margin: auto; margin-top: 150px; border: solid 1px #CCCCCC; padding: 10px;}
#error h1  { font-family: "Trebuchet MS", Arial, Helvetica, sans-serif; font-size: 18px; color: #333;}
#error div { font-family: Verdana, Geneva, sans-serif; font-size: 12px;}
.descricao { font-size: 12px; color: #F00;}
.descricao span { color: #666;}

</style>
</head>

<div id="error">
	<h1>Desculpe</h1>
    <div>Nosso servidor se comportou de maneira inesperada. Já recebemos o comunicado do erro e estamos trabalhando para que isso não aconteça novamente.</div>
    <? if(getenv('ERROR') == 'true'){ ?>
    <div class="descricao"></br><b>DESCRIÇÃO DO ERRO:</b> Controlador Não Encontrado. </br></br><span><?=$this->error;?></span></div>
    <? }?>
</div>

<body>
</body>
</html>